### ISSUE TITLE
Pasar anexos a latex

### ISSUE THREAD

**Issue by cgp1017** [cgp1017/Practica_1_0_2023_2024#15]
Anexos
 · Plan del proyecto software
 · Especificación de Requisitos
 · Especificación de diseño
 · Manual del programador
 · Manual de usuario
Expresión regular para corregir las referencias:

Buscar: (\{\[\})([\w:\\]+)(\{\]\}\\\_)
Reemplazar por: \\citep{\2}
Ej: {[}art:campbell2005{]}\_ -> \citep{art:campbell2005}

Expresión regular para corregir las imágenes:

Buscar: (\\includegraphics{..\/..\/img\/)(\w*)(.\w*\})
Reemplazar por: \\imagen{\2}{descripción...}
Ej: \includegraphics{../../img/s2.png} -> \imagen{s2}{descripción...}}

**Comment by cgp1017** [comment]
Todas sabéis utilizar Latex?

**Comment by maf1013** [comment]
Después de una segunda matrícula de informática lo tengo más que controlado

**Comment by vbm1007** [comment]
Yo no me acuerdo muy bien, pero me veo un video
