### ISSUE TITLE
Imprimir memoria

### ISSUE THREAD

**Issue by vbm1007** [cgp1017/Practica_1_0_2023_2024#4]
La memoria ha de estar encuadernada en formato:
Libro cosido
Libro pegado
Revista de tapa dura y grapa
No se deben utilizar tornillos, espirales, canutillos y similares.

**Comment by vbm1007** [comment]
Voy a la imprenta pero hay mucha cola

**Comment by maf1013** [comment]
No imprimas, que mi padre lo puede imprimir en el trabajo gratis

**Comment by cgp1017** [comment]
Genial, gracias Maria
