### ISSUE TITLE
Manual del programador

### ISSUE THREAD

**Issue by cgp1017** [cgp1017/Practica_1_0_2023_2024#6]
Instalación Android Studio
    Importación del proyecto
    Estructura directorios
    Ejecución tests en local
    Servicios de integración continua
    Creación de un ejecutable
    Plataforma de desarrollo del algoritmo
    Plataforma de conteo

**Comment by maf1013** [comment]
¿Alguna de vosotras ha podido instalar Android Studios? A mi no me deja

**Comment by roa1005** [comment]
Si actualizas la versión de tu dispositivo a la más nueva, podrás descargarlo sin problema María
